- src: 'git+https://github.com/JoergFiedler/freebsd-jailed-nginx.git'
  version: 'v2.2.0'
  name: 'JoergFiedler.freebsd-jailed-nginx'
- src: 'git+https://github.com/JoergFiedler/freebsd-jailed-mariadb.git'
  version: 'v1.2.0'
  name: 'JoergFiedler.freebsd-jailed-mariadb'
- src: 'git+https://github.com/JoergFiedler/freebsd-jailed.git'
  version: 'v2.2.0'
  name: 'JoergFiedler.freebsd-jailed'
- src: 'git+https://github.com/JoergFiedler/freebsd-jail-host.git'
  version: 'v3.2.0'
  name: 'JoergFiedler.freebsd-jail-host'
