- src: 'git+https://github.com/JoergFiedler/freebsd-jail-host.git'
  name: 'JoergFiedler.freebsd-jail-host'
- src: 'git+https://github.com/JoergFiedler/freebsd-jailed.git'
  name: 'JoergFiedler.freebsd-jailed'
- src: 'git+https://github.com/JoergFiedler/freebsd-jailed-nginx.git'
  name: 'JoergFiedler.freebsd-jailed-nginx'
- src: 'git+https://github.com/JoergFiedler/freebsd-jailed-mariadb.git'
  name: 'JoergFiedler.freebsd-jailed-mariadb'
