- src: 'git+https://github.com/JoergFiedler/freebsd-jailed-nginx.git'
  version: 'v3.3.0'
  name: 'JoergFiedler.freebsd-jailed-nginx'
- src: 'git+https://github.com/JoergFiedler/freebsd-jailed-mariadb.git'
  version: 'v1.2.4'
  name: 'JoergFiedler.freebsd-jailed-mariadb'
- src: 'git+https://github.com/JoergFiedler/freebsd-jail-host.git'
  version: 'v3.2.1'
  name: 'JoergFiedler.freebsd-jail-host'
