dist: xenial
language: python
python: 2.7
install:
- wget https://releases.hashicorp.com/vagrant/2.2.2/vagrant_2.2.2_x86_64.deb
- sudo dpkg -i vagrant_2.2.2_x86_64.deb
- pip install -r .requirements.txt
before_script:
- vagrant plugin install vagrant-aws
- ssh-keygen -y -f ~/.vagrant.d/insecure_private_key > ~/.vagrant.d/insecure_private_key.pub
- ln -s ./ JoergFiedler.freebsd-jailed-wordpress
script:
- yamllint .
- ansible-lint .
- ansible-galaxy install -fp ./ -r .requirements.yml
- vagrant box add JoergFiedler/FreeBSD-11.2 --provider aws
- vagrant up --provider aws
- host=$(vagrant ssh-config |grep HostName |awk '{print $2}')
- test $(curl -w %{http_code} https://${host}/wp-admin/install.php -o /dev/null
  --insecure) == "200"
- test $(sftp -P 10022 -o StrictHostKeyChecking=no -i ~/.vagrant.d/insecure_private_key
  sftp_local@${host} <<< $'ls -l' |grep webroot |wc -l) == "1"
after_script:
- vagrant destroy -f
env:
  global:
  - secure: Svh9FdLvR6SyFi7lzu6q4PyxkljQ6LVxMgxyObVcT76XSdIoC/ScTkyWFB4TYd3uHgYwBmeKe8E8DK74kDJfEkjso7+PSl+aSxxj94jAJmLZt12gB9OaP0S71E/qYxLkSJsEI3M5HOIJwu1yTPpjKc/07LBomqRhs5jTieopcC61dVrHaqdFzOEVMtMNZI88NcX9YmXA/5ea/UPgUVtiMQnw0ftVvigtO9c3+10EgOF4IlQZf22IZjGkTqdrAVB4+T5r5+M27YWZg/XA5o3vSeW88wPIF5iBtB/sY8HYuDk6/J5opJm7jvlg+4JtOUjRLetLJKQYzitjIEWr35KyYfUU+X6ihpvmfEhwRY9wO485slL3wxjTG04HHskgw8lXz2CypZHlEZ9R5QTlzGi1k7rqkmwX7b8Y5drga5KumOxsN82h6LPfQVPspcpDj+Ecb+OyLzJoyCZaGa/6WXOcu0F3If7yGkZWz0VpJz1tOOiJ2vJLFCDNmdHh7k9POHPb4bjdhFQtzVsXRs2cJgA9j0sp4U9BNgPoROZEImwn4EqU/F1N4LlTuQ9O8bwePiuwoQb5lfYD5vOoL7CONJjQRXIvuEdo4KGXZB6P1SZ2JIOrBVEtVdzK+w++6FCbxcyVMSkMuFXR+vxumxjpgNdAJMfifMjNIHNS3Zpe52AzhOQ=
  - secure: oeplbE+Tv3VBG6Z3HYfZCMhGmkwvdGDt4Vdr1F3LzVqyAnfJcV3dYnj+e58g4EQjNhA8yG3By7XkCCMbzrnDU2N53wzWUeiWlnPTXcNNMISsf9PGc1e96K2tdahIMBYDvSIiWo/M9uUjE550J0Ml1A9WPHJivF7mJT07sgh499f+300LGLjNSdghi3HCgKZs+jY7jWhFsueLdDWt5CbGkDhnpzE/7/TMiQrqx9dM+i4KzemiBikcNGnbAAcfyuc3oh3QxXMUcs5YzUAqy9RSvijWSA1szZ6v5eTC/d/f1d500xBE4NWq+oYaJAbvzG0Uz9LSmI6yMAFpGYz4/9YRuh1X/ZL4fqJRCRmbzLqj6QQzwrxeY/IWs9f/yQjKNfjEzwQnnfpT5UHrcJJaj3/vEbsDHrP0N/Ratd/wkv8mhJiBn4KBMPkv2rDnJo1UV0pYTJbPg8jt3qW/IncEBSADaKms5sw2LZkibvSOAzQ+k+VrXSckTI69oeDL/g4C0MDtExPpM+eCr6aMbSqOFDYul5Kcp9kfdGJLSYvU+tFolJC3uOPJOJJCzVmyEZKOEopesIX0el3ICQFVfh2hJvsdYhhhdCXGqtVePSEq7N/6O+e2YgcUYOMQHGU/aZb9LHO1oKjoOiOn3+NyvMpqUCfxrzr9iu7yEHLNSfLszdenzCQ=
