---
# tasks file for freebsd-jailed-wordpress
- include_tasks: wordpress.yml
  tags:
    - wordpress
- include_tasks: nginx-server.yml
  tags:
    - wordpress
- include_tasks: pf.yml
  tags:
    - wordpress
