---
- name: Install additional packages
  pkgng:
    name: '{{ item }}'
    state: present
  loop:
    - py36-mysqlclient
  register: pkg_result
  until: pkg_result is succeeded

- name: Create Wordpress database
  mysql_db:
    name: '{{ wp_db_name }}'
    login_host: '{{ wp_db_host }}'
    login_password: '{{ wp_db_host_password }}'
    login_user: '{{ wp_db_host_user }}'
    state: present

- name: Create MariaDB Wordpress user
  mysql_user:
    name: '{{ wp_db_user }}'
    encrypted: no
    host: '{{ jail_net_ip }}'
    login_host: '{{ wp_db_host }}'
    login_password: '{{ wp_db_host_password }}'
    login_user: '{{ wp_db_host_user }}'
    password: '{{ wp_db_password }}'
    priv: '{{ wp_db_priv }}'
    state: present

- name: Check if Wordpress Installation is present
  stat:
    path: '{{ wp_server_webroot_host_zfs_dir }}/wp-config.php'
  register: wp_config_file

- name: Download Wordpress
  become: false
  get_url:
    url: '{{ wp_download_url }}'
    dest: '/tmp/wordpress-latest.tar.gz'
  delegate_to: 127.0.0.1
  when: not wp_config_file.stat.exists

- name: Copy Wordpress package
  copy:
    src: '/tmp/wordpress-latest.tar.gz'
    dest: '/tmp/wordpress-latest.tar.gz'
  when: not wp_config_file.stat.exists

- name: Extract Wordpress package
  command: |
    /usr/bin/tar \
      -C {{ wp_server_webroot_host_zfs_dir }} \
      --strip-components 1 \
      -xzf /tmp/wordpress-latest.tar.gz
  when: not wp_config_file.stat.exists
  tags:
    - skip_ansible_lint

- name: Create tmp folder
  file:
    path: '{{ wp_server_webroot_host_zfs_dir }}/tmp'
    owner: '{{ wp_sftp_uuid }}'
    state: directory

- name: Generate keys and salts.
  become: false
  command: |
     curl {{ wp_key_salt_url }}
  register: wp_keys_salts
  changed_when: false
  delegate_to: 127.0.0.1
  when: not wp_config_file.stat.exists
  tags:
    - skip_ansible_lint

- name: Copy Wordpress configuration
  template:
    src: 'wp-config.php.j2'
    dest: '{{ wp_server_webroot_host_zfs_dir }}/wp-config.php'
  when: not wp_config_file.stat.exists

- name: Update webroot file permissions
  file:
    path: '{{ wp_server_webroot_host_zfs_dir }}'
    state: directory
    recurse: yes
    mode: 'u+rw,g-w,o-rwx'
    owner: '{{ wp_sftp_uuid }}'
    group: 'www'

- name: Delete obsolete files
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '{{ wp_server_webroot_host_zfs_dir }}/wp-config.php.sample'
    - '{{ wp_server_webroot_host_zfs_dir }}/wordpress'

- name: Delete obsolete file (local)
  become: false
  file:
    path: '/tmp/wordpress-latest.tar.gz'
    state: absent
  delegate_to: 127.0.0.1
